#!/usr/bin/env bash

# get bash colors and styles here:
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

function __run() #(step, name, cmd)
{
    local color output exitcode

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"
    output=$(eval "$3" 2>&1)
    exitcode=$?

    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
        printf "${C_YELLOW}[%s]${C_RESET}\n" "OK!"

    else
        printf "${C_RED}[%s]${C_RESET}\n\n[%s]" "NOK!" "$output"
        exit 1
    fi
}
dart_format="dart format --set-exit-if-changed"
dart_analyze="dart analyze"
modified="git diff --diff-filter=M --name-only --cached  | grep \".dart\""
__run "1/2" "Dart Format" "${modified} | xargs -r ${dart_format}"
__run "2/2" "Dart Analyze" "${modified} | xargs -r ${dart_analyze}"
