#!/usr/bin/env bash

# get bash colors and styles here:
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'
FVM="fvm"
function __run() #(step, name, cmd)
{
    local color output exitCode

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"
    output=$(eval "$3" 2>&1)
    exitCode=$?

    if [[ 0 == "$exitCode" || 130 == "$exitCode" ]]; then
        printf "${C_GREEN}[%s]${C_RESET}\n" "OK!"

    else
        printf "${C_RED}[%s]${C_RESET}\n[%s]" "NOK!" "$output"
        exit 1
    fi
}

dart_format="$FVM dart format --set-exit-if-changed"
dart_analyze="$FVM flutter analyze --fatal-infos --fatal-warnings"
modified="git diff --diff-filter=M --name-only --cached  | grep \".dart\""
__run "1/2" "Flutter Format" "${modified} | xargs -r ${dart_format}"
__run "2/2" "Flutter Analyze" "${dart_analyze}"
